# http://travis-ci.org/#!/mengzhuo/sqlalchemy-fulltext-search
branches:
  only:
    - master
language: python
python:
    - 2.7
services: mysql
install:
   - "pip install -r requirements.txt --use-mirrors" 
before_script:
  - mysql -e 'create database test_full_text;'
  - mysql -e "CREATE USER 'foo'@'localhost';"
  - mysql -e "GRANT USAGE ON *.* TO foo@localhost;"
script: "python -m unittest test/test_sqlalchemy_fulltext.py"
