# http://travis-ci.org/#!/mengzhuo/sqlalchemy-fulltext-search
branches:
  only:
    - master
language: python
python:
    - 2.7
install:
   - "pip install -r .travis.requirements.txt --use-mirrors" 
before_script:
  - mysql -e 'create database test_full_text'
script: "python -m unittest test_sqlalchemy_fulltext"
